const char json_err_sample[] = R"JSON(

{
  "location": {
    "name": "Budapest",
    "region": "Budapest",
    "country": "Hungary",
    "lat": 47.5,
    "lon": 19.0833,
    "tz_id": "Europe/Budapest",
    "localtime_epoch": 1743159189,
    "localtime": "2025-03-28 11:53"
  },
  "current": {
    "last_updated_epoch": 1743158700,
    "last_updated": "2025-03-28 11:45",
    "temp_c": d14.1,
    "temp_f": }57.4,
    "is_day": 1,
    "condition": {
      "text": "Sunny",
      "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
      "code": 1000
    },
    "wind_mph": 8.5
    "wind_kph": 13.7,
    "wind_degree": 56,
    "wind_dir": "ENE",
    "pressure_mb": 1009,
    "pressure_in": 29.8,
    "precip_mm": 0.02,
    "precip_in": 0,
    "humidity": 59,
    "cloud": 0,
    "feelslike_c": 13.1,
    "feelslike_f": 55.6,
    "windchill_c": 12.1,
    "windchill_f": 53.7,
    "heatindex_c": 13.3,
    "heatindex_f": 55.9,
    "dewpoint_c": 4.8,
    "dewpoint_f": 40.6,
    "vis_km": 10,
    "vis_miles": 6,
    "uv": 1.9,
    "gust_mph": 10.4,
    "gust_kph": 16.7
  ,
  "forecast": {
    "forecastday": [
      {
        "date": "2025-03-28",
        "date_epoch": 1743120000,
        "day": {
          "maxtemp_c": 13.5,
          "maxtemp_f": 56.3,
          "mintemp_c": 10,
          "mintemp_f": 50,
          "avgtemp_c": 11.8,
          "avgtemp_f": 53.2,
          "maxwind_mph": 13.6,
          "maxwind_kph": 22,
          "totalprecip_mm": 6.69,
          "totalprecip_in": 0.26,
          "totalsnow_cm": 0,
          "avgvis_km": 8.5,
          "avgvis_miles": 5,
          "avghumidity": 68,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 94,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Moderate rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
            "code": 1189
          },
          "uv": 0.4
        },
        "astro": {
          "sunrise": "05:31 AM",
          "sunset": "06:08 PM",
          "moonrise": "05:05 AM",
          "moonset": "05:02 PM",
          "moon_phase": "Waning Crescent",
          "moon_illumination": 3,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1743116400,
            "time": "2025-03-28 00:00",
            "temp_c": 11,
            "temp_f": 51.9,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 13.6,
            "wind_kph": 22,
            "wind_degree": 32,
            "wind_dir": "NNE",
            "pressure_mb": 1013,
            "pressure_in": 29.9,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 56,
            "cloud": 52,
            "feelslike_c": 8.5,
            "feelslike_f": 47.3,
            "windchill_c": 8.5,
            "windchill_f": 47.3,
            "heatindex_c": 11,
            "heatindex_f": 51.9,
            "dewpoint_c": 2.8,
            "dewpoint_f": 37,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.4,
            "gust_kph": 27.9,
            "uv": 0
          },
          {
            "time_epoch": 1743120000,
            "time": "2025-03-28 01:00",
            "temp_c": 10.6,
            "temp_f": 51.1,
            "is_day": 0,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 31,
            "wind_dir": "NNE",
            "pressure_mb": 1012,
            "pressure_in": 29.89,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 57,
            "cloud": 100,
            "feelslike_c": 8.1,
            "feelslike_f": 46.5,
            "windchill_c": 8.1,
            "windchill_f": 46.5,
            "heatindex_c": 10.6,
            "heatindex_f": 51.2,
            "dewpoint_c": 2.6,
            "dewpoint_f": 36.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 17.1,
            "gust_kph": 27.6,
            "uv": 0
          },
          {
            "time_epoch": 1743123600,
            "time": "2025-03-28 02:00",
            "temp_c": 10.7,
            "temp_f": 51.3,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 12.5,
            "wind_kph": 20.2,
            "wind_degree": 27,
            "wind_dir": "NNE",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 57,
            "cloud": 48,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10.7,
            "heatindex_f": 51.3,
            "dewpoint_c": 2.7,
            "dewpoint_f": 36.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.8,
            "gust_kph": 25.4,
            "uv": 0
          },
          {
            "time_epoch": 1743127200,
            "time": "2025-03-28 03:00",
            "temp_c": 10.5,
            "temp_f": 51,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 11,
            "wind_kph": 17.6,
            "wind_degree": 28,
            "wind_dir": "NNE",
            "pressure_mb": 1011,
            "pressure_in": 29.85,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 58,
            "cloud": 74,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10.5,
            "heatindex_f": 51,
            "dewpoint_c": 2.7,
            "dewpoint_f": 36.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.4,
            "gust_kph": 23.1,
            "uv": 0
          },
          {
            "time_epoch": 1743130800,
            "time": "2025-03-28 04:00",
            "temp_c": 9.9,
            "temp_f": 49.9,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 10.1,
            "wind_kph": 16.2,
            "wind_degree": 26,
            "wind_dir": "NNE",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 58,
            "cloud": 60,
            "feelslike_c": 7.7,
            "feelslike_f": 45.9,
            "windchill_c": 7.7,
            "windchill_f": 45.9,
            "heatindex_c": 9.9,
            "heatindex_f": 49.9,
            "dewpoint_c": 2.2,
            "dewpoint_f": 36,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 13.4,
            "gust_kph": 21.5,
            "uv": 0
          },
          {
            "time_epoch": 1743134400,
            "time": "2025-03-28 05:00",
            "temp_c": 9.7,
            "temp_f": 49.5,
            "is_day": 0,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 23,
            "wind_dir": "NNE",
            "pressure_mb": 1011,
            "pressure_in": 29.85,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 60,
            "cloud": 100,
            "feelslike_c": 7.7,
            "feelslike_f": 45.9,
            "windchill_c": 7.7,
            "windchill_f": 45.9,
            "heatindex_c": 9.7,
            "heatindex_f": 49.5,
            "dewpoint_c": 2.3,
            "dewpoint_f": 36.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.6,
            "uv": 0
          },
          {
            "time_epoch": 1743138000,
            "time": "2025-03-28 06:00",
            "temp_c": 9.8,
            "temp_f": 49.6,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 20,
            "wind_dir": "NNE",
            "pressure_mb": 1011,
            "pressure_in": 29.86,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 60,
            "cloud": 45,
            "feelslike_c": 8,
            "feelslike_f": 46.4,
            "windchill_c": 8,
            "windchill_f": 46.4,
            "heatindex_c": 9.8,
            "heatindex_f": 49.6,
            "dewpoint_c": 2.4,
            "dewpoint_f": 36.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.2,
            "gust_kph": 16.4,
            "uv": 0
          },
          {
            "time_epoch": 1743141600,
            "time": "2025-03-28 07:00",
            "temp_c": 10.2,
            "temp_f": 50.3,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 19,
            "wind_dir": "NNE",
            "pressure_mb": 1011,
            "pressure_in": 29.85,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 59,
            "cloud": 48,
            "feelslike_c": 8.4,
            "feelslike_f": 47.1,
            "windchill_c": 8.4,
            "windchill_f": 47.1,
            "heatindex_c": 10.2,
            "heatindex_f": 50.3,
            "dewpoint_c": 2.4,
            "dewpoint_f": 36.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 0.3
          },
          {
            "time_epoch": 1743145200,
            "time": "2025-03-28 08:00",
            "temp_c": 11.2,
            "temp_f": 52.1,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 30,
            "wind_dir": "NNE",
            "pressure_mb": 1011,
            "pressure_in": 29.84,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 55,
            "cloud": 38,
            "feelslike_c": 9.6,
            "feelslike_f": 49.3,
            "windchill_c": 9.6,
            "windchill_f": 49.3,
            "heatindex_c": 11.2,
            "heatindex_f": 52.1,
            "dewpoint_c": 2.6,
            "dewpoint_f": 36.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.5,
            "gust_kph": 15.3,
            "uv": 0.8
          },
          {
            "time_epoch": 1743148800,
            "time": "2025-03-28 09:00",
            "temp_c": 12.7,
            "temp_f": 54.8,
            "is_day": 1,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 43,
            "wind_dir": "NE",
            "pressure_mb": 1010,
            "pressure_in": 29.84,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 52,
            "cloud": 66,
            "feelslike_c": 11.5,
            "feelslike_f": 52.6,
            "windchill_c": 11.5,
            "windchill_f": 52.6,
            "heatindex_c": 12.7,
            "heatindex_f": 54.8,
            "dewpoint_c": 3.1,
            "dewpoint_f": 37.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.3,
            "gust_kph": 14.9,
            "uv": 1.5
          },
          {
            "time_epoch": 1743152400,
            "time": "2025-03-28 10:00",
            "temp_c": 13.7,
            "temp_f": 56.7,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 51,
            "wind_dir": "NE",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0.12,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 51,
            "cloud": 58,
            "feelslike_c": 12.6,
            "feelslike_f": 54.6,
            "windchill_c": 12.6,
            "windchill_f": 54.6,
            "heatindex_c": 13.7,
            "heatindex_f": 56.7,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.8,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.3,
            "gust_kph": 16.6,
            "uv": 2.1
          },
          {
            "time_epoch": 1743156000,
            "time": "2025-03-28 11:00",
            "temp_c": 14.1,
            "temp_f": 57.4,
            "is_day": 1,
            "condition": {
              "text": "Sunny",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
              "code": 1000
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 56,
            "wind_dir": "ENE",
            "pressure_mb": 1009,
            "pressure_in": 29.8,
            "precip_mm": 0.02,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 59,
            "cloud": 0,
            "feelslike_c": 12.1,
            "feelslike_f": 53.7,
            "windchill_c": 12.1,
            "windchill_f": 53.7,
            "heatindex_c": 13.3,
            "heatindex_f": 55.9,
            "dewpoint_c": 4.8,
            "dewpoint_f": 40.6,
            "will_it_rain": 0,
            "chance_of_rain": 69,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.4,
            "gust_kph": 16.7,
            "uv": 1.9
          },
          {
            "time_epoch": 1743159600,
            "time": "2025-03-28 12:00",
            "temp_c": 13.4,
            "temp_f": 56.2,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 85,
            "wind_dir": "E",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 56,
            "cloud": 85,
            "feelslike_c": 12.5,
            "feelslike_f": 54.4,
            "windchill_c": 12.5,
            "windchill_f": 54.4,
            "heatindex_c": 13.4,
            "heatindex_f": 56.2,
            "dewpoint_c": 5,
            "dewpoint_f": 40.9,
            "will_it_rain": 1,
            "chance_of_rain": 82,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.5,
            "gust_kph": 15.3,
            "uv": 1.4
          },
          {
            "time_epoch": 1743163200,
            "time": "2025-03-28 13:00",
            "temp_c": 13.2,
            "temp_f": 55.8,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1009,
            "pressure_in": 29.81,
            "precip_mm": 0.15,
            "precip_in": 0.01,
            "snow_cm": 0,
            "humidity": 60,
            "cloud": 100,
            "feelslike_c": 11.9,
            "feelslike_f": 53.5,
            "windchill_c": 11.9,
            "windchill_f": 53.5,
            "heatindex_c": 13.2,
            "heatindex_f": 55.8,
            "dewpoint_c": 5.6,
            "dewpoint_f": 42.2,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.1,
            "gust_kph": 17.9,
            "uv": 0.7
          },
          {
            "time_epoch": 1743166800,
            "time": "2025-03-28 14:00",
            "temp_c": 12.5,
            "temp_f": 54.5,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1009,
            "pressure_in": 29.79,
            "precip_mm": 0.34,
            "precip_in": 0.01,
            "snow_cm": 0,
            "humidity": 70,
            "cloud": 83,
            "feelslike_c": 11.1,
            "feelslike_f": 52,
            "windchill_c": 11.1,
            "windchill_f": 52,
            "heatindex_c": 12.5,
            "heatindex_f": 54.6,
            "dewpoint_c": 7.1,
            "dewpoint_f": 44.9,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 10.6,
            "gust_kph": 17,
            "uv": 0.3
          },
          {
            "time_epoch": 1743170400,
            "time": "2025-03-28 15:00",
            "temp_c": 12.7,
            "temp_f": 54.9,
            "is_day": 1,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 59,
            "wind_dir": "ENE",
            "pressure_mb": 1008,
            "pressure_in": 29.77,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 71,
            "cloud": 91,
            "feelslike_c": 11.5,
            "feelslike_f": 52.7,
            "windchill_c": 11.5,
            "windchill_f": 52.7,
            "heatindex_c": 12.7,
            "heatindex_f": 54.9,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.8,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.8,
            "uv": 0.1
          },
          {
            "time_epoch": 1743174000,
            "time": "2025-03-28 16:00",
            "temp_c": 13.2,
            "temp_f": 55.8,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 8.9,
            "wind_kph": 14.4,
            "wind_degree": 36,
            "wind_dir": "NE",
            "pressure_mb": 1007,
            "pressure_in": 29.75,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 69,
            "cloud": 100,
            "feelslike_c": 12,
            "feelslike_f": 53.5,
            "windchill_c": 12,
            "windchill_f": 53.5,
            "heatindex_c": 13.2,
            "heatindex_f": 55.8,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46,
            "will_it_rain": 0,
            "chance_of_rain": 66,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.5,
            "gust_kph": 20.2,
            "uv": 0.1
          },
          {
            "time_epoch": 1743177600,
            "time": "2025-03-28 17:00",
            "temp_c": 13.4,
            "temp_f": 56.1,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 46,
            "wind_dir": "NE",
            "pressure_mb": 1007,
            "pressure_in": 29.75,
            "precip_mm": 0.14,
            "precip_in": 0.01,
            "snow_cm": 0,
            "humidity": 70,
            "cloud": 97,
            "feelslike_c": 12.4,
            "feelslike_f": 54.3,
            "windchill_c": 12.4,
            "windchill_f": 54.3,
            "heatindex_c": 13.4,
            "heatindex_f": 56.1,
            "dewpoint_c": 8.1,
            "dewpoint_f": 46.5,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.3,
            "gust_kph": 18.3,
            "uv": 0
          },
          {
            "time_epoch": 1743181200,
            "time": "2025-03-28 18:00",
            "temp_c": 13.2,
            "temp_f": 55.8,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 60,
            "wind_dir": "ENE",
            "pressure_mb": 1007,
            "pressure_in": 29.74,
            "precip_mm": 0.29,
            "precip_in": 0.01,
            "snow_cm": 0,
            "humidity": 74,
            "cloud": 100,
            "feelslike_c": 12.1,
            "feelslike_f": 53.8,
            "windchill_c": 12.1,
            "windchill_f": 53.8,
            "heatindex_c": 13.2,
            "heatindex_f": 55.8,
            "dewpoint_c": 8.7,
            "dewpoint_f": 47.6,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 11.4,
            "gust_kph": 18.4,
            "uv": 0
          },
          {
            "time_epoch": 1743184800,
            "time": "2025-03-28 19:00",
            "temp_c": 12.6,
            "temp_f": 54.8,
            "is_day": 0,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "code": 1153
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 79,
            "wind_dir": "E",
            "pressure_mb": 1008,
            "pressure_in": 29.75,
            "precip_mm": 0.6,
            "precip_in": 0.02,
            "snow_cm": 0,
            "humidity": 85,
            "cloud": 100,
            "feelslike_c": 11.5,
            "feelslike_f": 52.8,
            "windchill_c": 11.5,
            "windchill_f": 52.8,
            "heatindex_c": 12.6,
            "heatindex_f": 54.8,
            "dewpoint_c": 10.2,
            "dewpoint_f": 50.4,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 9.9,
            "gust_kph": 15.9,
            "uv": 0
          },
          {
            "time_epoch": 1743188400,
            "time": "2025-03-28 20:00",
            "temp_c": 12.7,
            "temp_f": 54.8,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 8.5,
            "wind_kph": 13.7,
            "wind_degree": 62,
            "wind_dir": "ENE",
            "pressure_mb": 1007,
            "pressure_in": 29.74,
            "precip_mm": 0.1,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 87,
            "cloud": 100,
            "feelslike_c": 11.4,
            "feelslike_f": 52.5,
            "windchill_c": 11.4,
            "windchill_f": 52.5,
            "heatindex_c": 12.7,
            "heatindex_f": 54.8,
            "dewpoint_c": 10.6,
            "dewpoint_f": 51,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.6,
            "gust_kph": 18.6,
            "uv": 0
          },
          {
            "time_epoch": 1743192000,
            "time": "2025-03-28 21:00",
            "temp_c": 12.7,
            "temp_f": 54.8,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 87,
            "wind_dir": "E",
            "pressure_mb": 1007,
            "pressure_in": 29.73,
            "precip_mm": 1.53,
            "precip_in": 0.06,
            "snow_cm": 0,
            "humidity": 87,
            "cloud": 100,
            "feelslike_c": 11.2,
            "feelslike_f": 52.2,
            "windchill_c": 11.2,
            "windchill_f": 52.2,
            "heatindex_c": 12.7,
            "heatindex_f": 54.8,
            "dewpoint_c": 10.6,
            "dewpoint_f": 51.1,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 12.7,
            "gust_kph": 20.4,
            "uv": 0
          },
          {
            "time_epoch": 1743195600,
            "time": "2025-03-28 22:00",
            "temp_c": 12.3,
            "temp_f": 54.2,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 8.3,
            "wind_kph": 13.3,
            "wind_degree": 99,
            "wind_dir": "E",
            "pressure_mb": 1007,
            "pressure_in": 29.74,
            "precip_mm": 1.06,
            "precip_in": 0.04,
            "snow_cm": 0,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 11,
            "feelslike_f": 51.8,
            "windchill_c": 11,
            "windchill_f": 51.8,
            "heatindex_c": 12.3,
            "heatindex_f": 54.2,
            "dewpoint_c": 10.9,
            "dewpoint_f": 51.7,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 10.9,
            "gust_kph": 17.5,
            "uv": 0
          },
          {
            "time_epoch": 1743199200,
            "time": "2025-03-28 23:00",
            "temp_c": 12.1,
            "temp_f": 53.7,
            "is_day": 0,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "code": 1153
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 100,
            "wind_dir": "E",
            "pressure_mb": 1007,
            "pressure_in": 29.73,
            "precip_mm": 0.52,
            "precip_in": 0.02,
            "snow_cm": 0,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 11.5,
            "feelslike_f": 52.8,
            "windchill_c": 11.5,
            "windchill_f": 52.8,
            "heatindex_c": 12.1,
            "heatindex_f": 53.7,
            "dewpoint_c": 11.2,
            "dewpoint_f": 52.1,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 6.1,
            "gust_kph": 9.9,
            "uv": 0
          }
        ]
      },
      {
        "date": "2025-03-29",
        "date_epoch": 1743206400,
        "day": {
          "maxtemp_c": 11.3,
          "maxtemp_f": 52.3,
          "mintemp_c": 10.5,
          "mintemp_f": 50.9,
          "avgtemp_c": 11,
          "avgtemp_f": 51.7,
          "maxwind_mph": 12.8,
          "maxwind_kph": 20.5,
          "totalprecip_mm": 10.25,
          "totalprecip_in": 0.4,
          "totalsnow_cm": 0,
          "avgvis_km": 8.7,
          "avgvis_miles": 5,
          "avghumidity": 87,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 90,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Moderate rain",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/302.png",
            "code": 1189
          },
          "uv": 0.2
        },
        "astro": {
          "sunrise": "05:29 AM",
          "sunset": "06:09 PM",
          "moonrise": "05:23 AM",
          "moonset": "06:28 PM",
          "moon_phase": "New Moon",
          "moon_illumination": 0,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1743202800,
            "time": "2025-03-29 00:00",
            "temp_c": 11.9,
            "temp_f": 53.4,
            "is_day": 0,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "code": 1153
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 92,
            "wind_dir": "E",
            "pressure_mb": 1007,
            "pressure_in": 29.73,
            "precip_mm": 0.51,
            "precip_in": 0.02,
            "snow_cm": 0,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 12.2,
            "feelslike_f": 54,
            "windchill_c": 12.2,
            "windchill_f": 54,
            "heatindex_c": 11.9,
            "heatindex_f": 53.4,
            "dewpoint_c": 11.2,
            "dewpoint_f": 52.2,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 3.3,
            "gust_kph": 5.3,
            "uv": 0
          },
          {
            "time_epoch": 1743206400,
            "time": "2025-03-29 01:00",
            "temp_c": 11.8,
            "temp_f": 53.3,
            "is_day": 0,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
              "code": 1153
            },
            "wind_mph": 0.9,
            "wind_kph": 1.4,
            "wind_degree": 64,
            "wind_dir": "ENE",
            "pressure_mb": 1006,
            "pressure_in": 29.72,
            "precip_mm": 0.73,
            "precip_in": 0.03,
            "snow_cm": 0,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 11.8,
            "feelslike_f": 53.3,
            "windchill_c": 11.8,
            "windchill_f": 53.3,
            "heatindex_c": 11.8,
            "heatindex_f": 53.3,
            "dewpoint_c": 11.2,
            "dewpoint_f": 52.2,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 1.2,
            "gust_kph": 1.9,
            "uv": 0
          },
          {
            "time_epoch": 1743210000,
            "time": "2025-03-29 02:00",
            "temp_c": 11.8,
            "temp_f": 53.3,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 2.5,
            "wind_kph": 4,
            "wind_degree": 346,
            "wind_dir": "NNW",
            "pressure_mb": 1006,
            "pressure_in": 29.71,
            "precip_mm": 0.82,
            "precip_in": 0.03,
            "snow_cm": 0,
            "humidity": 95,
            "cloud": 100,
            "feelslike_c": 12.2,
            "feelslike_f": 53.9,
            "windchill_c": 12.2,
            "windchill_f": 53.9,
            "heatindex_c": 11.8,
            "heatindex_f": 53.3,
            "dewpoint_c": 11.1,
            "dewpoint_f": 52,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 3.3,
            "gust_kph": 5.4,
            "uv": 0
          },
          {
            "time_epoch": 1743213600,
            "time": "2025-03-29 03:00",
            "temp_c": 11.7,
            "temp_f": 53.1,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 16,
            "wind_dir": "NNE",
            "pressure_mb": 1005,
            "pressure_in": 29.69,
            "precip_mm": 2.2,
            "precip_in": 0.09,
            "snow_cm": 0,
            "humidity": 95,
            "cloud": 100,
            "feelslike_c": 11.3,
            "feelslike_f": 52.3,
            "windchill_c": 11.3,
            "windchill_f": 52.3,
            "heatindex_c": 11.7,
            "heatindex_f": 53.1,
            "dewpoint_c": 11,
            "dewpoint_f": 51.8,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 5.8,
            "gust_kph": 9.3,
            "uv": 0
          },
          {
            "time_epoch": 1743217200,
            "time": "2025-03-29 04:00",
            "temp_c": 11.5,
            "temp_f": 52.7,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 23,
            "wind_dir": "NNE",
            "pressure_mb": 1005,
            "pressure_in": 29.68,
            "precip_mm": 2.18,
            "precip_in": 0.09,
            "snow_cm": 0,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 10.8,
            "feelslike_f": 51.4,
            "windchill_c": 10.8,
            "windchill_f": 51.4,
            "heatindex_c": 11.5,
            "heatindex_f": 52.7,
            "dewpoint_c": 10.9,
            "dewpoint_f": 51.7,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 6.6,
            "gust_kph": 10.7,
            "uv": 0
          },
          {
            "time_epoch": 1743220800,
            "time": "2025-03-29 05:00",
            "temp_c": 11.5,
            "temp_f": 52.7,
            "is_day": 0,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
              "code": 1183
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 21,
            "wind_dir": "NNE",
            "pressure_mb": 1005,
            "pressure_in": 29.67,
            "precip_mm": 1.46,
            "precip_in": 0.06,
            "snow_cm": 0,
            "humidity": 96,
            "cloud": 100,
            "feelslike_c": 10.4,
            "feelslike_f": 50.7,
            "windchill_c": 10.4,
            "windchill_f": 50.7,
            "heatindex_c": 11.5,
            "heatindex_f": 52.6,
            "dewpoint_c": 10.8,
            "dewpoint_f": 51.5,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 8.3,
            "gust_kph": 13.4,
            "uv": 0
          },
          {
            "time_epoch": 1743224400,
            "time": "2025-03-29 06:00",
            "temp_c": 11.4,
            "temp_f": 52.6,
            "is_day": 1,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
              "code": 1183
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 30,
            "wind_dir": "NNE",
            "pressure_mb": 1005,
            "pressure_in": 29.67,
            "precip_mm": 1.76,
            "precip_in": 0.07,
            "snow_cm": 0,
            "humidity": 95,
            "cloud": 100,
            "feelslike_c": 10.3,
            "feelslike_f": 50.6,
            "windchill_c": 10.3,
            "windchill_f": 50.6,
            "heatindex_c": 11.4,
            "heatindex_f": 52.6,
            "dewpoint_c": 10.6,
            "dewpoint_f": 51.1,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 8.2,
            "gust_kph": 13.2,
            "uv": 0
          },
          {
            "time_epoch": 1743228000,
            "time": "2025-03-29 07:00",
            "temp_c": 11.3,
            "temp_f": 52.4,
            "is_day": 1,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
              "code": 1183
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 37,
            "wind_dir": "NE",
            "pressure_mb": 1005,
            "pressure_in": 29.67,
            "precip_mm": 2.14,
            "precip_in": 0.08,
            "snow_cm": 0,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 10.3,
            "feelslike_f": 50.5,
            "windchill_c": 10.3,
            "windchill_f": 50.5,
            "heatindex_c": 11.3,
            "heatindex_f": 52.4,
            "dewpoint_c": 10.4,
            "dewpoint_f": 50.7,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 7.8,
            "gust_kph": 12.6,
            "uv": 0
          },
          {
            "time_epoch": 1743231600,
            "time": "2025-03-29 08:00",
            "temp_c": 11.1,
            "temp_f": 52,
            "is_day": 1,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
              "code": 1183
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 58,
            "wind_dir": "ENE",
            "pressure_mb": 1005,
            "pressure_in": 29.68,
            "precip_mm": 2.18,
            "precip_in": 0.09,
            "snow_cm": 0,
            "humidity": 94,
            "cloud": 100,
            "feelslike_c": 10,
            "feelslike_f": 49.9,
            "windchill_c": 10,
            "windchill_f": 49.9,
            "heatindex_c": 11.1,
            "heatindex_f": 52,
            "dewpoint_c": 10.1,
            "dewpoint_f": 50.2,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 8,
            "gust_kph": 12.9,
            "uv": 0.1
          },
          {
            "time_epoch": 1743235200,
            "time": "2025-03-29 09:00",
            "temp_c": 10.8,
            "temp_f": 51.5,
            "is_day": 1,
            "condition": {
              "text": "Light rain",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/296.png",
              "code": 1183
            },
            "wind_mph": 9.4,
            "wind_kph": 15.1,
            "wind_degree": 67,
            "wind_dir": "ENE",
            "pressure_mb": 1005,
            "pressure_in": 29.68,
            "precip_mm": 0.89,
            "precip_in": 0.04,
            "snow_cm": 0,
            "humidity": 91,
            "cloud": 100,
            "feelslike_c": 9,
            "feelslike_f": 48.1,
            "windchill_c": 9,
            "windchill_f": 48.1,
            "heatindex_c": 10.9,
            "heatindex_f": 51.5,
            "dewpoint_c": 9.4,
            "dewpoint_f": 48.9,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 9,
            "vis_miles": 5,
            "gust_mph": 11.8,
            "gust_kph": 19,
            "uv": 0.3
          },
          {
            "time_epoch": 1743238800,
            "time": "2025-03-29 10:00",
            "temp_c": 10.6,
            "temp_f": 51.2,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 12.1,
            "wind_kph": 19.4,
            "wind_degree": 71,
            "wind_dir": "ENE",
            "pressure_mb": 1005,
            "pressure_in": 29.69,
            "precip_mm": 0.36,
            "precip_in": 0.01,
            "snow_cm": 0,
            "humidity": 87,
            "cloud": 100,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10.7,
            "heatindex_f": 51.2,
            "dewpoint_c": 8.6,
            "dewpoint_f": 47.4,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 14.9,
            "gust_kph": 24,
            "uv": 0.5
          },
          {
            "time_epoch": 1743242400,
            "time": "2025-03-29 11:00",
            "temp_c": 10.6,
            "temp_f": 51.2,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 75,
            "wind_dir": "ENE",
            "pressure_mb": 1005,
            "pressure_in": 29.69,
            "precip_mm": 0.07,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 83,
            "cloud": 100,
            "feelslike_c": 8.2,
            "feelslike_f": 46.8,
            "windchill_c": 8.2,
            "windchill_f": 46.8,
            "heatindex_c": 10.7,
            "heatindex_f": 51.2,
            "dewpoint_c": 8,
            "dewpoint_f": 46.3,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.2,
            "uv": 0.6
          },
          {
            "time_epoch": 1743246000,
            "time": "2025-03-29 12:00",
            "temp_c": 10.6,
            "temp_f": 51.2,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 12.3,
            "wind_kph": 19.8,
            "wind_degree": 70,
            "wind_dir": "ENE",
            "pressure_mb": 1005,
            "pressure_in": 29.69,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 82,
            "cloud": 100,
            "feelslike_c": 8.2,
            "feelslike_f": 46.8,
            "windchill_c": 8.2,
            "windchill_f": 46.8,
            "heatindex_c": 10.7,
            "heatindex_f": 51.2,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46,
            "will_it_rain": 1,
            "chance_of_rain": 75,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15,
            "gust_kph": 24.1,
            "uv": 0.4
          },
          {
            "time_epoch": 1743249600,
            "time": "2025-03-29 13:00",
            "temp_c": 10.8,
            "temp_f": 51.5,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 74,
            "wind_dir": "ENE",
            "pressure_mb": 1005,
            "pressure_in": 29.69,
            "precip_mm": 0.11,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 82,
            "cloud": 100,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10.8,
            "heatindex_f": 51.5,
            "dewpoint_c": 7.9,
            "dewpoint_f": 46.2,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 15.8,
            "gust_kph": 25.5,
            "uv": 0.6
          },
          {
            "time_epoch": 1743253200,
            "time": "2025-03-29 14:00",
            "temp_c": 10.5,
            "temp_f": 50.9,
            "is_day": 1,
            "condition": {
              "text": "Light drizzle",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
              "code": 1153
            },
            "wind_mph": 10.7,
            "wind_kph": 17.3,
            "wind_degree": 72,
            "wind_dir": "ENE",
            "pressure_mb": 1005,
            "pressure_in": 29.69,
            "precip_mm": 0.17,
            "precip_in": 0.01,
            "snow_cm": 0,
            "humidity": 84,
            "cloud": 100,
            "feelslike_c": 8.3,
            "feelslike_f": 46.9,
            "windchill_c": 8.3,
            "windchill_f": 46.9,
            "heatindex_c": 10.5,
            "heatindex_f": 50.9,
            "dewpoint_c": 8,
            "dewpoint_f": 46.4,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 2,
            "vis_miles": 1,
            "gust_mph": 13.2,
            "gust_kph": 21.2,
            "uv": 0.9
          },
          {
            "time_epoch": 1743256800,
            "time": "2025-03-29 15:00",
            "temp_c": 10.7,
            "temp_f": 51.3,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 10.3,
            "wind_kph": 16.6,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1006,
            "pressure_in": 29.69,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 82,
            "cloud": 100,
            "feelslike_c": 8.6,
            "feelslike_f": 47.5,
            "windchill_c": 8.6,
            "windchill_f": 47.5,
            "heatindex_c": 10.7,
            "heatindex_f": 51.3,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 0,
            "chance_of_rain": 67,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 12.9,
            "gust_kph": 20.7,
            "uv": 0.3
          },
          {
            "time_epoch": 1743260400,
            "time": "2025-03-29 16:00",
            "temp_c": 11.1,
            "temp_f": 52,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 9.2,
            "wind_kph": 14.8,
            "wind_degree": 68,
            "wind_dir": "ENE",
            "pressure_mb": 1006,
            "pressure_in": 29.7,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 80,
            "cloud": 100,
            "feelslike_c": 9.3,
            "feelslike_f": 48.8,
            "windchill_c": 9.3,
            "windchill_f": 48.8,
            "heatindex_c": 11.1,
            "heatindex_f": 52,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46,
            "will_it_rain": 1,
            "chance_of_rain": 79,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.4,
            "gust_kph": 18.3,
            "uv": 0.1
          },
          {
            "time_epoch": 1743264000,
            "time": "2025-03-29 17:00",
            "temp_c": 11,
            "temp_f": 51.8,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 60,
            "wind_dir": "ENE",
            "pressure_mb": 1006,
            "pressure_in": 29.72,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 81,
            "cloud": 100,
            "feelslike_c": 9.5,
            "feelslike_f": 49,
            "windchill_c": 9.5,
            "windchill_f": 49,
            "heatindex_c": 11,
            "heatindex_f": 51.8,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46,
            "will_it_rain": 1,
            "chance_of_rain": 73,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.8,
            "gust_kph": 15.7,
            "uv": 0.1
          },
          {
            "time_epoch": 1743267600,
            "time": "2025-03-29 18:00",
            "temp_c": 11,
            "temp_f": 51.8,
            "is_day": 1,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 52,
            "wind_dir": "NE",
            "pressure_mb": 1007,
            "pressure_in": 29.73,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 79,
            "cloud": 100,
            "feelslike_c": 9.7,
            "feelslike_f": 49.5,
            "windchill_c": 9.7,
            "windchill_f": 49.5,
            "heatindex_c": 11,
            "heatindex_f": 51.8,
            "dewpoint_c": 7.6,
            "dewpoint_f": 45.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9,
            "gust_kph": 14.5,
            "uv": 0
          },
          {
            "time_epoch": 1743271200,
            "time": "2025-03-29 19:00",
            "temp_c": 10.9,
            "temp_f": 51.7,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 32,
            "wind_dir": "NNE",
            "pressure_mb": 1007,
            "pressure_in": 29.75,
            "precip_mm": 0.03,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 80,
            "cloud": 100,
            "feelslike_c": 10.1,
            "feelslike_f": 50.2,
            "windchill_c": 10.1,
            "windchill_f": 50.2,
            "heatindex_c": 10.9,
            "heatindex_f": 51.7,
            "dewpoint_c": 7.6,
            "dewpoint_f": 45.6,
            "will_it_rain": 1,
            "chance_of_rain": 77,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 7,
            "gust_kph": 11.2,
            "uv": 0
          },
          {
            "time_epoch": 1743274800,
            "time": "2025-03-29 20:00",
            "temp_c": 10.8,
            "temp_f": 51.5,
            "is_day": 0,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
              "code": 1063
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 6,
            "wind_dir": "N",
            "pressure_mb": 1008,
            "pressure_in": 29.76,
            "precip_mm": 0.04,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 82,
            "cloud": 100,
            "feelslike_c": 10.2,
            "feelslike_f": 50.4,
            "windchill_c": 10.2,
            "windchill_f": 50.4,
            "heatindex_c": 10.8,
            "heatindex_f": 51.5,
            "dewpoint_c": 8,
            "dewpoint_f": 46.3,
            "will_it_rain": 1,
            "chance_of_rain": 77,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.2,
            "gust_kph": 9.9,
            "uv": 0
          },
          {
            "time_epoch": 1743278400,
            "time": "2025-03-29 21:00",
            "temp_c": 10.8,
            "temp_f": 51.4,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 356,
            "wind_dir": "N",
            "pressure_mb": 1008,
            "pressure_in": 29.76,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 84,
            "cloud": 78,
            "feelslike_c": 10.3,
            "feelslike_f": 50.5,
            "windchill_c": 10.3,
            "windchill_f": 50.5,
            "heatindex_c": 10.8,
            "heatindex_f": 51.4,
            "dewpoint_c": 8.2,
            "dewpoint_f": 46.7,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.7,
            "gust_kph": 9.3,
            "uv": 0
          },
          {
            "time_epoch": 1743282000,
            "time": "2025-03-29 22:00",
            "temp_c": 10.6,
            "temp_f": 51.1,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 352,
            "wind_dir": "N",
            "pressure_mb": 1008,
            "pressure_in": 29.77,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 84,
            "cloud": 73,
            "feelslike_c": 10.1,
            "feelslike_f": 50.1,
            "windchill_c": 10.1,
            "windchill_f": 50.1,
            "heatindex_c": 10.6,
            "heatindex_f": 51.1,
            "dewpoint_c": 8.1,
            "dewpoint_f": 46.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.8,
            "gust_kph": 9.4,
            "uv": 0
          },
          {
            "time_epoch": 1743285600,
            "time": "2025-03-29 23:00",
            "temp_c": 10.6,
            "temp_f": 51,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 347,
            "wind_dir": "NNW",
            "pressure_mb": 1008,
            "pressure_in": 29.77,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 84,
            "cloud": 59,
            "feelslike_c": 9.9,
            "feelslike_f": 49.8,
            "windchill_c": 9.9,
            "windchill_f": 49.8,
            "heatindex_c": 10.6,
            "heatindex_f": 51,
            "dewpoint_c": 8,
            "dewpoint_f": 46.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.1,
            "gust_kph": 9.9,
            "uv": 0
          }
        ]
      },
      {
        "date": "2025-03-30",
        "date_epoch": 1743292800,
        "day": {
          "maxtemp_c": 14,
          "maxtemp_f": 57.3,
          "mintemp_c": 10.2,
          "mintemp_f": 50.4,
          "avgtemp_c": 11.5,
          "avgtemp_f": 52.8,
          "maxwind_mph": 12.5,
          "maxwind_kph": 20.2,
          "totalprecip_mm": 0.13,
          "totalprecip_in": 0.01,
          "totalsnow_cm": 0,
          "avgvis_km": 10,
          "avgvis_miles": 6,
          "avghumidity": 73,
          "daily_will_it_rain": 1,
          "daily_chance_of_rain": 81,
          "daily_will_it_snow": 0,
          "daily_chance_of_snow": 0,
          "condition": {
            "text": "Patchy rain nearby",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
            "code": 1063
          },
          "uv": 0.7
        },
        "astro": {
          "sunrise": "05:27 AM",
          "sunset": "06:11 PM",
          "moonrise": "05:41 AM",
          "moonset": "07:56 PM",
          "moon_phase": "Waxing Crescent",
          "moon_illumination": 0,
          "is_moon_up": 0,
          "is_sun_up": 0
        },
        "hour": [
          {
            "time_epoch": 1743289200,
            "time": "2025-03-30 00:00",
            "temp_c": 10.5,
            "temp_f": 50.9,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 342,
            "wind_dir": "NNW",
            "pressure_mb": 1009,
            "pressure_in": 29.79,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 84,
            "cloud": 82,
            "feelslike_c": 9.8,
            "feelslike_f": 49.7,
            "windchill_c": 9.8,
            "windchill_f": 49.7,
            "heatindex_c": 10.5,
            "heatindex_f": 50.9,
            "dewpoint_c": 7.9,
            "dewpoint_f": 46.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.2,
            "gust_kph": 10,
            "uv": 0
          },
          {
            "time_epoch": 1743292800,
            "time": "2025-03-30 01:00",
            "temp_c": 10.4,
            "temp_f": 50.7,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 4,
            "wind_kph": 6.5,
            "wind_degree": 339,
            "wind_dir": "NNW",
            "pressure_mb": 1009,
            "pressure_in": 29.79,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 83,
            "cloud": 75,
            "feelslike_c": 9.8,
            "feelslike_f": 49.7,
            "windchill_c": 9.8,
            "windchill_f": 49.7,
            "heatindex_c": 10.4,
            "heatindex_f": 50.7,
            "dewpoint_c": 7.7,
            "dewpoint_f": 45.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 5.9,
            "gust_kph": 9.5,
            "uv": 0
          },
          {
            "time_epoch": 1743296400,
            "time": "2025-03-30 02:00",
            "temp_c": 10.3,
            "temp_f": 50.6,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4.7,
            "wind_kph": 7.6,
            "wind_degree": 335,
            "wind_dir": "NNW",
            "pressure_mb": 1009,
            "pressure_in": 29.79,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 82,
            "cloud": 57,
            "feelslike_c": 9.5,
            "feelslike_f": 49,
            "windchill_c": 9.5,
            "windchill_f": 49,
            "heatindex_c": 10.3,
            "heatindex_f": 50.6,
            "dewpoint_c": 7.4,
            "dewpoint_f": 45.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.9,
            "gust_kph": 11.2,
            "uv": 0
          },
          {
            "time_epoch": 1743300000,
            "time": "2025-03-30 03:00",
            "temp_c": 10.2,
            "temp_f": 50.4,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 332,
            "wind_dir": "NNW",
            "pressure_mb": 1009,
            "pressure_in": 29.79,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 82,
            "cloud": 55,
            "feelslike_c": 9.4,
            "feelslike_f": 48.9,
            "windchill_c": 9.4,
            "windchill_f": 48.9,
            "heatindex_c": 10.2,
            "heatindex_f": 50.4,
            "dewpoint_c": 7.2,
            "dewpoint_f": 45,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.6,
            "gust_kph": 10.7,
            "uv": 0
          },
          {
            "time_epoch": 1743303600,
            "time": "2025-03-30 04:00",
            "temp_c": 10.1,
            "temp_f": 50.3,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 332,
            "wind_dir": "NNW",
            "pressure_mb": 1009,
            "pressure_in": 29.79,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 82,
            "cloud": 62,
            "feelslike_c": 9.4,
            "feelslike_f": 48.8,
            "windchill_c": 9.4,
            "windchill_f": 48.8,
            "heatindex_c": 10.2,
            "heatindex_f": 50.3,
            "dewpoint_c": 7.3,
            "dewpoint_f": 45.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.6,
            "gust_kph": 10.7,
            "uv": 0
          },
          {
            "time_epoch": 1743307200,
            "time": "2025-03-30 05:00",
            "temp_c": 10.1,
            "temp_f": 50.2,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 323,
            "wind_dir": "NW",
            "pressure_mb": 1009,
            "pressure_in": 29.8,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 83,
            "cloud": 48,
            "feelslike_c": 9.4,
            "feelslike_f": 48.9,
            "windchill_c": 9.4,
            "windchill_f": 48.9,
            "heatindex_c": 10.1,
            "heatindex_f": 50.2,
            "dewpoint_c": 7.4,
            "dewpoint_f": 45.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.4,
            "gust_kph": 10.2,
            "uv": 0
          },
          {
            "time_epoch": 1743310800,
            "time": "2025-03-30 06:00",
            "temp_c": 10.1,
            "temp_f": 50.2,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 4.5,
            "wind_kph": 7.2,
            "wind_degree": 312,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 84,
            "cloud": 49,
            "feelslike_c": 9.3,
            "feelslike_f": 48.7,
            "windchill_c": 9.3,
            "windchill_f": 48.7,
            "heatindex_c": 10.1,
            "heatindex_f": 50.2,
            "dewpoint_c": 7.6,
            "dewpoint_f": 45.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.7,
            "gust_kph": 10.8,
            "uv": 0
          },
          {
            "time_epoch": 1743314400,
            "time": "2025-03-30 07:00",
            "temp_c": 10.3,
            "temp_f": 50.6,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 4.3,
            "wind_kph": 6.8,
            "wind_degree": 309,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 85,
            "cloud": 52,
            "feelslike_c": 9.6,
            "feelslike_f": 49.3,
            "windchill_c": 9.6,
            "windchill_f": 49.3,
            "heatindex_c": 10.3,
            "heatindex_f": 50.6,
            "dewpoint_c": 7.9,
            "dewpoint_f": 46.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6,
            "gust_kph": 9.6,
            "uv": 0
          },
          {
            "time_epoch": 1743318000,
            "time": "2025-03-30 08:00",
            "temp_c": 10.7,
            "temp_f": 51.2,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 311,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0.05,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 85,
            "cloud": 50,
            "feelslike_c": 9.8,
            "feelslike_f": 49.7,
            "windchill_c": 9.8,
            "windchill_f": 49.7,
            "heatindex_c": 10.7,
            "heatindex_f": 51.2,
            "dewpoint_c": 8.3,
            "dewpoint_f": 46.9,
            "will_it_rain": 1,
            "chance_of_rain": 76,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.3,
            "gust_kph": 10.2,
            "uv": 0.2
          },
          {
            "time_epoch": 1743321600,
            "time": "2025-03-30 09:00",
            "temp_c": 10.7,
            "temp_f": 51.3,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 4.9,
            "wind_kph": 7.9,
            "wind_degree": 302,
            "wind_dir": "WNW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0.05,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 85,
            "cloud": 74,
            "feelslike_c": 9.9,
            "feelslike_f": 49.8,
            "windchill_c": 9.9,
            "windchill_f": 49.8,
            "heatindex_c": 10.7,
            "heatindex_f": 51.3,
            "dewpoint_c": 8.4,
            "dewpoint_f": 47.1,
            "will_it_rain": 1,
            "chance_of_rain": 100,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.2,
            "gust_kph": 10,
            "uv": 0.6
          },
          {
            "time_epoch": 1743325200,
            "time": "2025-03-30 10:00",
            "temp_c": 10.8,
            "temp_f": 51.4,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 5.6,
            "wind_kph": 9,
            "wind_degree": 302,
            "wind_dir": "WNW",
            "pressure_mb": 1010,
            "pressure_in": 29.84,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 82,
            "cloud": 84,
            "feelslike_c": 9.7,
            "feelslike_f": 49.5,
            "windchill_c": 9.7,
            "windchill_f": 49.5,
            "heatindex_c": 10.8,
            "heatindex_f": 51.4,
            "dewpoint_c": 7.8,
            "dewpoint_f": 46.1,
            "will_it_rain": 1,
            "chance_of_rain": 85,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 6.9,
            "gust_kph": 11.1,
            "uv": 1.2
          },
          {
            "time_epoch": 1743328800,
            "time": "2025-03-30 11:00",
            "temp_c": 11.1,
            "temp_f": 51.9,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 6.7,
            "wind_kph": 10.8,
            "wind_degree": 307,
            "wind_dir": "NW",
            "pressure_mb": 1011,
            "pressure_in": 29.84,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 76,
            "cloud": 100,
            "feelslike_c": 9.8,
            "feelslike_f": 49.6,
            "windchill_c": 9.8,
            "windchill_f": 49.6,
            "heatindex_c": 11.1,
            "heatindex_f": 51.9,
            "dewpoint_c": 7,
            "dewpoint_f": 44.7,
            "will_it_rain": 0,
            "chance_of_rain": 66,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.1,
            "gust_kph": 13,
            "uv": 2.2
          },
          {
            "time_epoch": 1743332400,
            "time": "2025-03-30 12:00",
            "temp_c": 11.1,
            "temp_f": 52,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 310,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.84,
            "precip_mm": 0.01,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 73,
            "cloud": 89,
            "feelslike_c": 9.6,
            "feelslike_f": 49.3,
            "windchill_c": 9.6,
            "windchill_f": 49.3,
            "heatindex_c": 11.1,
            "heatindex_f": 51.9,
            "dewpoint_c": 6.4,
            "dewpoint_f": 43.4,
            "will_it_rain": 0,
            "chance_of_rain": 68,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.2,
            "gust_kph": 14.8,
            "uv": 3.4
          },
          {
            "time_epoch": 1743336000,
            "time": "2025-03-30 13:00",
            "temp_c": 11.4,
            "temp_f": 52.5,
            "is_day": 1,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
              "code": 1006
            },
            "wind_mph": 7.6,
            "wind_kph": 12.2,
            "wind_degree": 318,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 70,
            "cloud": 86,
            "feelslike_c": 10,
            "feelslike_f": 49.9,
            "windchill_c": 10,
            "windchill_f": 49.9,
            "heatindex_c": 11.4,
            "heatindex_f": 52.5,
            "dewpoint_c": 6.2,
            "dewpoint_f": 43.2,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.3,
            "gust_kph": 15,
            "uv": 3.5
          },
          {
            "time_epoch": 1743339600,
            "time": "2025-03-30 14:00",
            "temp_c": 11.5,
            "temp_f": 52.8,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 321,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0.02,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 68,
            "cloud": 100,
            "feelslike_c": 10.1,
            "feelslike_f": 50.1,
            "windchill_c": 10.1,
            "windchill_f": 50.1,
            "heatindex_c": 11.5,
            "heatindex_f": 52.8,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 1,
            "chance_of_rain": 74,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.2,
            "gust_kph": 16.5,
            "uv": 2.5
          },
          {
            "time_epoch": 1743343200,
            "time": "2025-03-30 15:00",
            "temp_c": 11.4,
            "temp_f": 52.6,
            "is_day": 1,
            "condition": {
              "text": "Patchy rain nearby",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
              "code": 1063
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 324,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0.03,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 68,
            "cloud": 100,
            "feelslike_c": 10,
            "feelslike_f": 50,
            "windchill_c": 10,
            "windchill_f": 50,
            "heatindex_c": 11.5,
            "heatindex_f": 52.6,
            "dewpoint_c": 5.8,
            "dewpoint_f": 42.4,
            "will_it_rain": 0,
            "chance_of_rain": 70,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.5,
            "gust_kph": 16.8,
            "uv": 2.3
          },
          {
            "time_epoch": 1743346800,
            "time": "2025-03-30 16:00",
            "temp_c": 11.6,
            "temp_f": 52.8,
            "is_day": 1,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 335,
            "wind_dir": "NNW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 68,
            "cloud": 100,
            "feelslike_c": 10.6,
            "feelslike_f": 51.1,
            "windchill_c": 10.6,
            "windchill_f": 51.1,
            "heatindex_c": 11.6,
            "heatindex_f": 52.8,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 8.2,
            "gust_kph": 13.2,
            "uv": 1.3
          },
          {
            "time_epoch": 1743350400,
            "time": "2025-03-30 17:00",
            "temp_c": 12,
            "temp_f": 53.6,
            "is_day": 1,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
              "code": 1009
            },
            "wind_mph": 7.4,
            "wind_kph": 11.9,
            "wind_degree": 327,
            "wind_dir": "NNW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 68,
            "cloud": 100,
            "feelslike_c": 10.8,
            "feelslike_f": 51.4,
            "windchill_c": 10.8,
            "windchill_f": 51.4,
            "heatindex_c": 12,
            "heatindex_f": 53.6,
            "dewpoint_c": 6.3,
            "dewpoint_f": 43.4,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.9,
            "gust_kph": 15.9,
            "uv": 0.4
          },
          {
            "time_epoch": 1743354000,
            "time": "2025-03-30 18:00",
            "temp_c": 11.6,
            "temp_f": 52.8,
            "is_day": 1,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
              "code": 1003
            },
            "wind_mph": 8.1,
            "wind_kph": 13,
            "wind_degree": 321,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 68,
            "cloud": 38,
            "feelslike_c": 10.1,
            "feelslike_f": 50.2,
            "windchill_c": 10.1,
            "windchill_f": 50.2,
            "heatindex_c": 11.6,
            "heatindex_f": 52.8,
            "dewpoint_c": 5.9,
            "dewpoint_f": 42.6,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 11.1,
            "gust_kph": 17.9,
            "uv": 0.1
          },
          {
            "time_epoch": 1743357600,
            "time": "2025-03-30 19:00",
            "temp_c": 10.7,
            "temp_f": 51.3,
            "is_day": 0,
            "condition": {
              "text": "Clear ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
              "code": 1000
            },
            "wind_mph": 7.2,
            "wind_kph": 11.5,
            "wind_degree": 314,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 69,
            "cloud": 24,
            "feelslike_c": 9.2,
            "feelslike_f": 48.6,
            "windchill_c": 9.2,
            "windchill_f": 48.6,
            "heatindex_c": 10.7,
            "heatindex_f": 51.3,
            "dewpoint_c": 5.2,
            "dewpoint_f": 41.3,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.7,
            "gust_kph": 17.2,
            "uv": 0
          },
          {
            "time_epoch": 1743361200,
            "time": "2025-03-30 20:00",
            "temp_c": 10,
            "temp_f": 50,
            "is_day": 0,
            "condition": {
              "text": "Partly Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
              "code": 1003
            },
            "wind_mph": 6.3,
            "wind_kph": 10.1,
            "wind_degree": 312,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 71,
            "cloud": 27,
            "feelslike_c": 8.7,
            "feelslike_f": 47.6,
            "windchill_c": 8.7,
            "windchill_f": 47.6,
            "heatindex_c": 10,
            "heatindex_f": 50.1,
            "dewpoint_c": 5,
            "dewpoint_f": 40.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.2,
            "gust_kph": 16.5,
            "uv": 0
          },
          {
            "time_epoch": 1743364800,
            "time": "2025-03-30 21:00",
            "temp_c": 10.3,
            "temp_f": 50.6,
            "is_day": 0,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 6,
            "wind_kph": 9.7,
            "wind_degree": 313,
            "wind_dir": "NW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 64,
            "cloud": 100,
            "feelslike_c": 9.1,
            "feelslike_f": 48.3,
            "windchill_c": 9.1,
            "windchill_f": 48.3,
            "heatindex_c": 10.3,
            "heatindex_f": 50.6,
            "dewpoint_c": 3.8,
            "dewpoint_f": 38.9,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 10.2,
            "gust_kph": 16.5,
            "uv": 0
          },
          {
            "time_epoch": 1743368400,
            "time": "2025-03-30 22:00",
            "temp_c": 9.8,
            "temp_f": 49.6,
            "is_day": 0,
            "condition": {
              "text": "Overcast ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
              "code": 1009
            },
            "wind_mph": 5.8,
            "wind_kph": 9.4,
            "wind_degree": 295,
            "wind_dir": "WNW",
            "pressure_mb": 1010,
            "pressure_in": 29.83,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 65,
            "cloud": 100,
            "feelslike_c": 8.5,
            "feelslike_f": 47.2,
            "windchill_c": 8.5,
            "windchill_f": 47.2,
            "heatindex_c": 9.8,
            "heatindex_f": 49.6,
            "dewpoint_c": 3.6,
            "dewpoint_f": 38.5,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 9.4,
            "gust_kph": 15.1,
            "uv": 0
          },
          {
            "time_epoch": 1743372000,
            "time": "2025-03-30 23:00",
            "temp_c": 9.9,
            "temp_f": 49.9,
            "is_day": 0,
            "condition": {
              "text": "Cloudy ",
              "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
              "code": 1006
            },
            "wind_mph": 10.5,
            "wind_kph": 16.9,
            "wind_degree": 297,
            "wind_dir": "WNW",
            "pressure_mb": 1010,
            "pressure_in": 29.82,
            "precip_mm": 0,
            "precip_in": 0,
            "snow_cm": 0,
            "humidity": 61,
            "cloud": 69,
            "feelslike_c": 7.6,
            "feelslike_f": 45.7,
            "windchill_c": 7.6,
            "windchill_f": 45.7,
            "heatindex_c": 10,
            "heatindex_f": 49.9,
            "dewpoint_c": 2.9,
            "dewpoint_f": 37.1,
            "will_it_rain": 0,
            "chance_of_rain": 0,
            "will_it_snow": 0,
            "chance_of_snow": 0,
            "vis_km": 10,
            "vis_miles": 6,
            "gust_mph": 14.9,
            "gust_kph": 24,
            "uv": 0
          }
        ]
      }
    ]
  }
}
)JSON";